selenium-hub:
  image: selenium/hub
  container_name: 'selenium-hub'
  ports:
    - 4444:4444

chrome:
  image: selenium/node-chrome-debug
  container_name: 'chrome'
  links:
    - selenium-hub:hub
  ports:
    - 5900:5900
  volumes:
    - /dev/shm:/dev/shm

app:
  build: '.'
  container_name: 'app'
  links:
    - selenium-hub:hub
  volumes:
    - ./app/:/root/workdir
  environment:
    - 'TZ=Asia/Tokyo'
  tty: true
